# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calldmrs_turbo <- function(DMLresult, p_threshold = 1e-5, minlen = 50L, minCG = 3L, dis_merge = 100, pct_sig = 0.5, sep = 5000) {
    .Call(`_methylTracer_calldmrs_turbo`, DMLresult, p_threshold, minlen, minCG, dis_merge, pct_sig, sep)
}

computeStatCpp <- function(mean_1, mean_2, var1, var2) {
    .Call(`_methylTracer_computeStatCpp`, mean_1, mean_2, var1, var2)
}

fill_missing_with_mean <- function(chunk, chunk_mean) {
    .Call(`_methylTracer_fill_missing_with_mean`, chunk, chunk_mean)
}

